FROM webdevops/php-nginx:8.2-alpine

ENV WEB_DOCUMENT_ROOT=/app/public

WORKDIR /app

COPY composer.json composer.lock

RUN composer install --no-interaction --optimize-autoloader --no-dev

COPY . .

RUN php artisan optimize

RUN chown -R application:application .
